# 以下以一个构建vue项目的yml文件为例子
name: Auto Deploy
on:
  push:
    branches:
      - main # 这里只配置了main分支，所以只有推送main分支才会触发以下任务
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # 将代码拉取到虚拟机
        uses: actions/checkout@v3
        ref: main

      - name: Install and Build   # 安装依赖、打包，如果提前已打包好无需这一步
        run: |
          npm install
          npm run build

      - name: Deploy   # 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: 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
          repository-name: ywbo/mwiki.github.io
          branch: main # 部署后提交到那个分支
          folder: public
          commit-message: '${{ github.event.head_commit.message }} Updated By Github Actions'